site_name: MK Docs
nav:
- About: about.md
- Index: index.md
- Tools:
  - Tools: Tools/Tools.md
- Helm_chart:
  - Helm_chart: Helm_chart/Helm_chart.md
- Docker:
  - Commands: docker/commands.md
- Aws-boto:
  - Assume role lambda: AWS-boto/Assume-role-lambda.md
  - References: AWS-boto/references.md
- Python:
  - Basics: Python/basics.md
  - Python: Python/python.md
  - Setup: Python/setup.md
- Python/learn:
  - Week_1_fundamentals: Python/Learn/Week_1_Fundamentals.md
- Serverless:
  - Architechblog: Serverless/ArchitechBlog.md
  - Installation: Serverless/Installation.md
  - Lambda: Serverless/Lambda.md
  - Patterns: Serverless/Patterns.md
  - Serverless framework: Serverless/Serverless-framework.md
  - Blackfire: Serverless/blackfire.md
  - Configure: Serverless/configure.md
- Nas:
  - Tools: NAS/Tools.md
- Projects/redirection:
  - Notes: Projects/Redirection/Notes.md
  - Refrences: Projects/Redirection/Refrences.md
- Percona:
  - Commands: percona/commands.md
- Snowflake:
  - Snowflake odbc: Snowflake/snowflake-odbc.md
  - Snowqueries: Snowflake/snowqueries.md
  - Snowsql: Snowflake/snowsql.md
- Eks:
  - Service_mesh: EKS/Service_mesh.md
- Eks/ec2-iam:
  - Ec2  iam_access: EKS/ec2-iam/EC2--IAM_access.md
- Nginx:
  - Readme: Nginx/README.md
- Linux:
  - Linux terminal profile: linux/Linux-terminal-profile.md
  - Mega.cli: linux/Mega.cli.md
  - Openvpn: linux/OpenVpn.md
  - Python: linux/Python.md
  - Readme: linux/README.md
  - Vnc server: linux/VNC-server.md
  - Aws.centos7: linux/aws.centos7.md
  - Cmds: linux/cmds.md
  - Code server: linux/code-server.md
  - Firewalld: linux/firewalld.md
  - Php fpm: linux/php-fpm.md
  - Posffix: linux/posffix.md
  - Process_moniter: linux/process_moniter.md
  - Rbash: linux/rbash.md
  - Rsync: linux/rsync.md
  - Screen: linux/screen.md
  - Sftp: linux/sftp.md
  - Shell_restrict: linux/shell_restrict.md
  - Squid: linux/squid.md
  - Ssh keygen: linux/ssh-keygen.md
  - Sshd: linux/sshd.md
- Shell-script:
  - Tips: shell-script/Tips.md
  - Loop_webiste: shell-script/loop_webiste.md
  - Roadmap: shell-script/roadmap.md
  - Shell script: shell-script/shell-script.md
- Mysql:
  - Mysql.cnf: Mysql/mysql.cnf.md
- Aws:
  - Amazon kinesis: AWS/Amazon-Kinesis.md
  - Aws athena: AWS/Aws-Athena.md
  - Aws well architech: AWS/Aws-well-architech.md
  - Ci cd: AWS/CI-CD.md
  - Dms: AWS/DMS.md
  - Databases: AWS/Databases.md
  - Dynamodb: AWS/Dynamodb.md
  - Ec2: AWS/EC2.md
  - Iam: AWS/IAM.md
  - Nat_instance: AWS/Nat_instance.md
  - Rds: AWS/RDS.md
  - Sqs: AWS/Sqs.md
  - Tls migration: AWS/TLS-migration.md
  - Amazon linux: AWS/amazon-linux.md
  - Aws_clean_rooms: AWS/aws_clean_rooms.md
  - Bot fake crawler bots: AWS/bot-fake-crawler-bots.md
  - Codepipeline: AWS/codepipeline.md
  - Lambda: AWS/lambda.md
  - Mysqld: AWS/mysqld.md
  - Remote ec2: AWS/remote-ec2.md
  - S3 bucket: AWS/s3-bucket.md
  - Soci: AWS/soci.md
  - Waf: AWS/waf.md
  - Workshops: AWS/workshops.md
- Aws/exam-prep:
  - Readme: AWS/exam-prep/readme.md
- Aws/architectures:
  - Refernce_links: AWS/Architectures/Refernce_links.md
- Aws/iam/policies:
  - Code.commit: AWS/iam/policies/code.commit.md
  - Lambda assume role: AWS/iam/policies/lambda-assume-role.md
  - Switch role: AWS/iam/policies/switch-role.md
- Aws/topics:
  - Ebs: AWS/Topics/EBS.md
- Mkdocs:
  - Reference: Mkdocs/reference.md
- Kubernetes:
  - Cheatsheet: Kubernetes/CheatSheet.md
  - Cluster.prerequisite: Kubernetes/Cluster.Prerequisite.md
  - Links: Kubernetes/Links.md
  - Readme: Kubernetes/Readme.md
  - Topics: Kubernetes/Topics.md
  - Api: Kubernetes/api.md
  - Basics: Kubernetes/basics.md
  - Commands: Kubernetes/commands.md
  - Initialize.commands: Kubernetes/initialize.commands.md
- Kubernetes/selenium:
  - Cluster.prerequisite: Kubernetes/selenium/Cluster.Prerequisite.md
  - Readme: Kubernetes/selenium/Readme.md
- Kubernetes/cluster_setup:
  - Local_cluster_setup: Kubernetes/Cluster_Setup/Local_Cluster_Setup.md
- Git:
  - Multiple_commit_to_one: git/Multiple_Commit_To_One.md
  - Git: git/git.md
- Questions:
  - Docker: questions/Docker.md
  - Linux qst: questions/Linux-qst.md
  - Objects: questions/Objects.md
  - Python: questions/Python.md
  - Int: questions/int.md
  - Kubernetes int: questions/kubernetes-int.md
  - Kubernetes: questions/kubernetes.md
  - Q1: questions/q1.md
  - Terraform: questions/terraform.md
- Questions/terraform:
  - Terraform_cheat_sheet: questions/Terraform/Terraform_cheat_sheet.md
- Questions/python:
  - Log_tail: questions/Python/log_tail.md
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - content.tabs.link
  - content.code.copy
  - content.tabs.link
  plugins:
  - glightbox
markdown_extensions:
- admonition
- pymdownx.critic
- pymdownx.superfences
- footnotes
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- attr_list
- md_in_html
- admonition
- pymdownx.details
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: null
