apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-chrome-scaledobject
  namespace: default
  labels:
    deploymentName: selenium-chrome-node
spec:
  minReplicaCount: 2
  maxReplicaCount: 50
  scaleTargetRef:
    name: selenium-chrome-node
  triggers:
    - type: selenium-grid
      metadata:
        # url: 'http://selenium-hub:4444/graphql'
        url: 'http://selenium-hub.default.svc:4444/graphql'
        browserName: 'chrome'
